export const GET_PRODUCT_LIST_REQUEST = 'GET_PRODUCT_LIST_REQUEST';
export const GET_PRODUCT_LIST_REQUEST_SUCCESS = 'GET_PRODUCT_LIST_REQUEST_SUCCESS';
export const GET_RODUCT_LIST_REQUEST_FAILURE ='GET_RODUCT_LIST_REQUEST_FAILURE';

export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CATEGORY_LIST_REQUEST_SUCCESS = 'GET_CATEGORY_LIST_REQUEST_SUCCESS';
export const GET_CATEGORY_LIST_REQUEST_FAILURE ='GET_CATEGORY_LIST_REQUEST_FAILURE';


export const CREATE_CATEGORY_REQUEST = 'CREATE_CATEGORY_REQUEST';
export const CREATE_CATEGORY_REQUEST_SUCCESS = 'CREATE_CATEGORY_REQUEST_SUCCESS';
export const CREATE_CATEGORY_REQUEST_FAILURE ='CREATE_CATEGORY_REQUEST_FAILURE';

export const RESET_ACTION='RESET_ACTION';

// export {
//   GET_ALL_USER_INFO_REQUEST,
//   GET_ALL_USER_INFO_REQUEST_SUCCESS,
//   GET_ALL_USER_INFO_REQUEST_FAILURE,
// };